### ISSUE TITLE
Guest-Role: Error 500 when clicking "Logbücher"

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#123]
If I enter curriculum as guest I get an error 500 when I try to open "Logbücher".

ErrorException
Trying to get property 'id' of non-object (View: [PATH]/laravel-curriculum-adminlte3/resources/views/logbooks/index.blade.php)
https://[URL]/logbooks

**Comment by joachimdieterich** [comment]
Guests should not see logbooks, nor logbook-links. I think there is a missing permission check. 
On which page was the logbook link?

**Comment by Shen** [comment]
> On which page was the logbook link?
https://[URL]/home
![guest-logbook](https://user-images.githubusercontent.com/81589/102725534-acf55480-4317-11eb-914e-2c7748bffc6d.png)

**Comment by michaellass** [comment]
This issue is still not fixed. After re-initializing the database, the `permission_role` table is filled accordingly. The `Guest` role has only permissions `curriculum_show` and `navigator_show`. However, after login as Guest, there is still the logbook menu item and clicking on it still leads to the exception.
