### ISSUE TITLE
Certificates: usability

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#141]
I have found a example-template for certificates here: https://[URL]/documentation/1.0.de/pdf
But I don't understand how it works.
A documentation how to design templates would be helpful at all.
Much better would be a kind of template-generator where you are able to design a template and fill it with placeholders.
Where am I able to delete/edit existing templates?

**Comment by joachimdieterich** [comment]
The Template-generator is planned.

**Comment by joachimdieterich** [comment]
Certificates can now be created in the frontend.  
You will find this option under the endpoint /curriculum/{id}. 
This leads you to /certificates/create
There you can
- use predefined placeholders 
- or insert an image. Then select the picture and click on "Progress" in the toolbar. In the dialogue you can now select a Curricula, TerminalObjectives or EnablingObjectives and a percentage. If a learner has reached the percentage (green/orange) on the selected objective/curriculum), the picture will appear on the certificate, otherwise it will be displayed transparently.
