### ISSUE TITLE
Feature request: more customizable curricula

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#153]
**Is your feature request related to a problem? Please describe.**
I don't really know how to map a curriculum like this one with Curriculum. 
![lehrplan-deutsch-beispiel](https://user-images.githubusercontent.com/81589/103622908-a41b9a00-4f37-11eb-9a11-d89b67c0a54d.png)
(Source: https://www.schulentwicklung.nrw.de/lehrplaene/upload/klp_gs/vb/ps_d_lpentwurf_vb_2020_12_04.pdf)

**Describe the solution you'd like**
There are missing options like subheadings and subcategories for example. 
Each of the listed competencies should be assessable individually. But to create a separate module for each competency would be confusing. It would therefore be necessary to have the option of making several assessments within a module. Perhaps the module design is not suitable for every need...

**Comment by joachimdieterich** [comment]
The problem here is that the curriculum was not created for digital use. 
When digitising, it is important to ensure that the resulting grid is also easy to read on mobile devices. 
In the example above, I would make one curriculum for "competence expectations at the end of the school entry phase" - and a second curriculum for the "competence expectations at the end of class 4".

I would use as TerminalObjective (German "Bereich") the heading "Über Lesefähigkeit verfügen". 
As EnablingObjectives the individual bullet points "Students identify frequently recurring morphemes..." etc. 

Additional content, files, cross-references can be added to the objectives as needed. 

We can have a web session in which I show examples from Rhineland-Palatinate.

**Comment by joachimdieterich** [comment]
Merging with "Feature Request: Individual curricula #140"
